### ISSUE TITLE
Null bytes appended to AOF file during brutal VM shutdown

### ISSUE THREAD

**Issue by jimconner** [pivotal-cf/cf-redis-release#71] opened 2019-03-21 10:42 UTC
We recently encountered an issue where our NATS certificates expired and BOSH was not able to talk to its agents anymore. We resolved that issue by generating new NATS certs on the director and then running a `bosh cck`. Because the bosh director had no way to talk to the agents, it had no choice but to shoot the unresponsive VMs in the head and build new ones.

When the redis VM came back up, one of the redis instances on there failed to start up due to a corrupt AOF file. Examining the AOF file in an editor, it appeared that the every transaction had correctly been recorded in the AOF file, but there were 12 null 0x00 bytes appended to the file after the last transaction. Running the `redis-check-aof --fix <file.aof>` command quickly fixed the problem and the instance was then able to start.

The redis.conf already has the options enabled for loading truncated AOF file, but in this case the file was not truncated, but contained extra invalid bytes at the end.

A few days after we'd hit that problem, we were faced with the same situation again when the next set of NATS certs expired in a totally different CF deployment. Once again, when the vm was recreated by a `bosh cck` one of the redis AOF files had a few extra null bytes appended to the end and the instance was unable to start.... and once again, running the redis-check-aof file fixed things in a fraction of a second and got everything up and running again.

I've been contemplating raising a PR against cf-redis-release with a minor tweak to the prestart.erb template along the following lines...

```
fixtool=$(find /var/vcap/packages/redis/ -name redis-check-aof -print -quit)
find /var/vcap/store/cf-redis-broker/redis-data -name appendonly.aof | xargs -n 1 ${fixtool} --fix
```

Although it's a simple fix, it would ensure that all of the AOF files would be checked each time redis gets started.

I thought that rather than just raise the PR, I'd open an issue first to discuss the approach to the problem - I suspect that someone who knows Redis better than me might have a more elegant fix to offer than my shoddy bash script tweaks.

**Comment by jplebre** [comment] 2019-03-22 14:39
Hi @jimconner thanks for submitting the issue, and taking the time to describe steps to reproduce it, and include suggestions for a solution.

AFAIK I don't think we've seen this issue pop up on our fleets, so I'd like to give it a quick sanity check on our end. We've recently ran some interesting chaos engineering games and did not see this occur.

Could you give us some details of your deployment please?
- Redis version you are running (current version should be `4.0.14` or `5.0.4`). 
- Affected Redis instances were shared-vm or dedicated-vm, or both?
- When you say `[BOSH] had no choice but to shoot the unresponsive VMs in the head and build new ones.` I'm assuming the affected service instances were dedicated and not shared? Or perhaps the whole broker vm was destroyed?
- What snapshot strategy do you have in place, i.e aof only, or aof + rdb backups?
- What is `redis.snapshotting.rdb_checksum` set to in your deployments.

Note that there there is a known issue when using both aof and rdb, and rdb_checksum option is set to NO. In Redis < 4.0.10, checksum bites will be added to the files regardless if option is set to NO or YES, but if the checksum is set to NO, redis does not know how to parse them on startup). This has been registered in Redis issue #4902, apparently fixed in 4.0.10 but I can't easily confirm. 

I'm assuming, when the instances with the broken AOF files boot up, you are seeing something along the lines of:
```
[DATE] # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

My next step was to have a quick look to try and see if there might be any issues adding this check to the pre-start scripts:
* The first thing that comes to mind is the necessity of user input when running the command https://github.com/antirez/redis/issues/5378. We can possibly get around it with more bash scripting but it feels a bit like a smell to me.
* The other thing is that according to a few issues on the Redis github page, the `aof-load-truncated` property should fix these exact situations. We currently hardcode that to YES on our releases. It will only fail if the data is corrupted in the middle. That makes sense compared to the results we had of a few of our own testing.
* Maybe the solution would be to give ways to more gracefully shut down, within the drain scripts. Or document ways to ensure drain scripts are run for orphaned instances. The PCF-Redis docs include some information on how to manually backup/run errands and scripts, or how to deal with orphaned instances, but I'm aware these are not easily reachable from here, but that still feels like it could be potentially the best way to proceed.

Given these last two bits, I'm tempted to suggest that if such occurrence happens, I'd rather see the very specific Redis error message and leave up to the OP what kind of recovery I want to do: i.e. if I want to load from an alternate backup (e.g. rdb) or a prior backup, but would like to hear about the specifics of your setup so we can give this some thought. 

I've made a few notes and will bring this to the rest of the team. Do let me know if you can give us more details about your current configuration.

Thank you!
Joao

**Comment by jimconner** [comment] 2019-03-22 16:01
Hi @jplebre - Thanks for coming back to me.

The issue shouldn't really have happened with our fleets either, but somehow or other we'd missed the bosh NATS certs in our array of SSL certificate expiry check, so we unexpectedly found that BOSH couldn't talk to anything one day.... Ah well.. lesson learned now :-)

Here's the extra information.

* We're currently on cf-redis-release v343.0.16 which includes redis 4.0.11 (we will update real-soon-now)
* It is a shared-redis VM - We don't have any dedicated instances. The shared-vm had around 45 redis instances running on it, and only one of them had a problem. One of the apps on our platform is heavily reliant on redis, and there's a fair chance that it had a transaction in progress when the vm was recreated.
* When I said `shoot the unresponsive VMs` I was a little unclear - There is only a single shared redis vm which runs the broker and redis service. Bosh had to shoot all of the VMs it had deployed because they all used the same NATS cert - however, only a single one of them was for redis.
* Snapshotting stragegy is aof+rdb backups (I think it is... we're not changing it from the default)
* redis.snapshotting.rdb_checksum is set to yes (default value)

Your assumption about what we're seeing is 100% correct - It is that error message. We were only seeing it on a single redis instance each time it happened though.. the other 44 instances on the same shared-vm started up without any problems.

* I didn't think about the possibility of user input required for the `redis-check-aof` command. It has been a few weeks since the problem occurred... We put a story into our kanban to investigate ways to prevent the same thing happening again, but due to a busy backlog, we're only just playing this story now. You make a fine point about it being smelly.
* `aof-load-truncated` was the first thing I reached for when picking up this story, but checking in the redis.conf on the shared-vm, it appears that option is already enabled by default.
* Graceful shut down would not have been possible in the case where this happened to us. Because NATS certs had expired, BOSH director was unable to communicate  with any of it's agents, so there wouldn't have been a way of triggering the drain scripts (I may be wrong, but I think the vsphere CAPI uses PowerOff operation rather then sending a shutdown signal to the OS on the VM)

Re-occurence is unlikely to happen now as we've now beefed up our ssl cert expiry checks with the ones that we'd overlooked before, so we definitely won't be caught out the same way again - however it is easy to generate an AOF file with the same null bytes appended to the end for testing purposes.

I wonder if actually this is a bugfix/feature-request required for the `aof-load-truncated` function in redis rather than something that should be fixed with bash script workarounds.

**Comment by jplebre** [comment] 2019-03-22 17:27
Hey @jimconner 👋 

Thanks for the clarification.
RE: graceful shutdown, good point on the `I may be wrong, but I think the vsphere CAPI uses PowerOff operation rather then sending a shutdown signal to the OS on the VM` I'm not actually sure about vsphere details, and you are probably correct that this might not work across all platform offerings.

I'll see if the rest of the team has any ideas, but I'm leaning towards trying to replicate and see if can get enough info out of the box to get an issue to the redis core team. As you say, the best path may be a fix/request for the `aof-load-truncated` function.

**Comment by jplebre** [comment] 2019-03-27 09:54
Hey @jimconner 

We've tried using some extreme bosh shutdowns (like `bosh stop --hard` and `bosh delete-vm`) and in all cases it seems that `aof-load-truncated yes` managed to recover the file.

In discussion with the team we are of the opinion that since the error message is so explicit and the failure to recover seems to be such an edge that the operator should make the manual intervention and decide wether to try and run `redis-check-aof --fix` or potentially try other methods of restore (eg. an older snapshot).

If you still have details of the incident and maybe the aof file in question it might be worth raising this as a `aof-load-truncated` bug in redis itself, as you've mentioned in your previous post.

Feel free to re-open if new information comes to light

**Closed by jplebre** 2019-03-27 09:54 UTC
Labels: in progress
