### ISSUE TITLE
New Tile/BOSH Deployment installs fail

### ISSUE THREAD

**Issue by wayneeseguin** [pivotal-cf/cf-redis-release#39] opened 2016-11-23 14:13 UTC
Because of process destroyer. It has impacted both PCF tile clients on the latest tile version as of today as well as a couple of OSS folks using this release have reported it.

In order to 'unstick' the deployment it is required to ssh onto the VM and manually stop process deployer and then deploy again.

**Comment by jhunt** [comment] 2016-11-23 14:20
The root cause of the problem seems to be that `pkill` exits non-zero when there was nothing to kill (vs. having something to kill, but not being able to).  This runs afoul of the `-e` in the shebang, and causes the `stop` action to exit incorrectly, halting the bosh deployment.

I fixed this on a client site in two different ways.  One was to drop the `-e` altogether.  The other was to add an `|| true` after the `pkill` call.

**Comment by thereses** [comment] 2016-11-24 15:17
Does the issue occur during a fresh install or during an upgrade? The process destroyer shouldn't be called during a fresh install. 
We have scheduled an investigation of the issue.

**Comment by jhunt** [comment] 2016-11-26 03:04
IIRC, if the first deploy completes successfully, there is no problem.  But if there are any issues (IaaS, misconfiguration, CF unreachable, etc.), subsequent re-deploys engage the process-destroyer and leads to the failure.  I can verify early next week.

**Comment by thereses** [comment] 2016-11-28 15:07
Thanks, that's really helpful. If you do have any more info, please let us know. We will look into it this week.

**Comment by wayneeseguin** [comment] 2016-12-16 20:03
bump... When can we expect a new release with this fixed? Thank you!

**Comment by thereses** [comment] 2016-12-19 11:39
Hi Wayne, 
We have committed a fix for this. Which release or tile are you looking for?
thanks,
Therese

**Closed by thereses** 2016-12-19 11:39 UTC
Labels: accepted
